version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started...
      - npm run build

artifacts:
  base-directory: dist
  files:
    - '**/*'
